swagger: '2.0'
info:
  title: task_manager API
  description: "Документация для приложения task проекта task_manager"
  contact:
    email: egor-fipu@yandex.ru
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
paths:
  /auth/:
    post:
      operationId: auth_create
      description: 'Регистрация пользователя'
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: ''
          schema:
            properties:
              username:
                type: string
              full_name:
                type: string
      tags:
        - auth
    parameters: []
  /auth/token/:
    post:
      operationId: auth_get_token
      description: 'Получение токена'
      parameters:
        - name: data
          in: body
          required: true
          schema:
            properties:
              username:
                type: string
              password:
                type: string
      responses:
        '201':
          description: ''
          schema:
            properties:
              token:
                type: string
      tags:
        - auth
    parameters: []
  /tasks/:
    get:
      operationId: tasks_list
      description: "Список задач"
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Task'
      tags:
        - tasks
    post:
      operationId: tasks_create
      description: "Создание задачи"
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Task'
      tags:
        - tasks
    parameters: []
  /tasks/my/:
    get:
      operationId: tasks_get_my_tasks
      description: "Список задач, созданных пользователем"
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Task'
      tags:
        - tasks
    parameters: []
  /tasks/{id}/:
    get:
      operationId: tasks_read
      description: "Получение задачи по id"
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Task'
      tags:
        - tasks
    put:
      operationId: tasks_update
      description: "Обновление задачи"
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Task'
      tags:
        - tasks
    patch:
      operationId: tasks_partial_update
      description: "Обновление задачи"
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Task'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Task'
      tags:
        - tasks
    delete:
      operationId: tasks_delete
      description: "Удаление задачи"
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - tasks
    parameters:
      - name: id
        in: path
        description: "A unique integer value identifying this \u0417\u0430\u0434\u0430\
          \u0447\u0430."
        required: true
        type: integer
definitions:
  User:
    required:
      - username
      - password
      - full_name
    type: object
    properties:
      username:
        title: Username
        description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
          only.
        type: string
        pattern: ^[\w.@+-]+$
        maxLength: 150
        minLength: 1
      password:
        title: Password
        type: string
        maxLength: 128
        minLength: 1
      full_name:
        title: "\u041F\u043E\u043B\u043D\u043E\u0435 \u0438\u043C\u044F"
        type: string
        maxLength: 30
        minLength: 1
  Task:
    required:
      - performers
      - title
      - description
      - finished
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      author:
        title: Author
        type: string
        pattern: ^[\w.@+-]+$
        readOnly: true
      performers:
        type: array
        items:
          type: string
          pattern: ^[\w.@+-]+$
        uniqueItems: true
      title:
        title: "\u041D\u0430\u0437\u0432\u0430\u043D\u0438\u0435"
        type: string
        maxLength: 200
        minLength: 1
      description:
        title: "\u041E\u043F\u0438\u0441\u0430\u043D\u0438\u0435"
        type: string
        maxLength: 400
        minLength: 1
      finished:
        title: "\u041F\u043B\u0430\u043D\u0438\u0440\u0443\u0435\u043C\u0430\u044F\
          \ \u0434\u0430\u0442\u0430 \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043D\
          \u0438\u044F"
        type: string
        format: date
      file:
        title: "\u041F\u0440\u0438\u043A\u0440\u0435\u043F\u043B\u0435\u043D\u043D\
          \u044B\u0439 \u0444\u0430\u0439\u043B"
        type: string
        readOnly: true
        x-nullable: true
        format: uri
